package jcdragons.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBabyDragon extends ModelBase
{
  //fields
    ModelRenderer Snout;
    ModelRenderer LargeHornRight;
    ModelRenderer TuftEdgeRight;
    ModelRenderer BackLegRight;
    ModelRenderer SmallHornRight;
    ModelRenderer LargeHornLeft;
    ModelRenderer SmallHornLeft;
    ModelRenderer Head;
    ModelRenderer TuftRight;
    ModelRenderer TuftLeft;
    ModelRenderer TuftEdgeLeft;
    ModelRenderer TailBack;
    ModelRenderer BackLegLeft;
    ModelRenderer FrontLegRight;
    ModelRenderer PawBackLeft;
    ModelRenderer TailFurEdge;
    ModelRenderer Neck;
    ModelRenderer TailMiddle;
    ModelRenderer FrontLegLeft;
    ModelRenderer PawFrontLeft;
    ModelRenderer PawFrontRight;
    ModelRenderer PawBackRight;
    ModelRenderer Body;
    ModelRenderer BackFur;
    ModelRenderer TailMiddleFur;
    ModelRenderer TailBackFur;
    ModelRenderer Collar;
    ModelRenderer CollarBell;
  
  public ModelBabyDragon()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Snout = new ModelRenderer(this, 0, 0);
      Snout.addBox(0F, 0F, 0F, 3, 2, 3);
      Snout.setRotationPoint(-2F, 17F, -12F);
      Snout.setTextureSize(64, 64);
      Snout.mirror = true;
      setRotation(Snout, 0F, 0F, 0F);
      LargeHornRight = new ModelRenderer(this, 49, 0);
      LargeHornRight.addBox(0F, 0F, 0F, 1, 5, 1);
      LargeHornRight.setRotationPoint(2F, 10F, -6F);
      LargeHornRight.setTextureSize(64, 64);
      LargeHornRight.mirror = true;
      setRotation(LargeHornRight, 0F, 0F, 0.2230717F);
      TuftEdgeRight = new ModelRenderer(this, 9, 8);
      TuftEdgeRight.addBox(0F, 0F, 0F, 1, 2, 1);
      TuftEdgeRight.setRotationPoint(4F, 15F, -6F);
      TuftEdgeRight.setTextureSize(64, 64);
      TuftEdgeRight.mirror = true;
      setRotation(TuftEdgeRight, 0F, 0F, 0F);
      BackLegRight = new ModelRenderer(this, 9, 31);
      BackLegRight.addBox(0F, 0F, 0F, 2, 5, 2);
      BackLegRight.setRotationPoint(0F, 19F, 5F);
      BackLegRight.setTextureSize(64, 64);
      BackLegRight.mirror = true;
      setRotation(BackLegRight, 0F, 0F, 0F);
      SmallHornRight = new ModelRenderer(this, 49, 7);
      SmallHornRight.addBox(0F, 0F, 0F, 1, 3, 1);
      SmallHornRight.setRotationPoint(1F, 12F, -7F);
      SmallHornRight.setTextureSize(64, 64);
      SmallHornRight.mirror = true;
      setRotation(SmallHornRight, 0F, 0F, 0.2230705F);
      LargeHornLeft = new ModelRenderer(this, 44, 0);
      LargeHornLeft.addBox(0F, 0F, 0F, 1, 5, 1);
      LargeHornLeft.setRotationPoint(-4F, 10F, -6F);
      LargeHornLeft.setTextureSize(64, 64);
      LargeHornLeft.mirror = true;
      setRotation(LargeHornLeft, 0F, 0F, -0.2230705F);
      SmallHornLeft = new ModelRenderer(this, 44, 7);
      SmallHornLeft.addBox(0F, 0F, 0F, 1, 3, 1);
      SmallHornLeft.setRotationPoint(-3F, 12F, -7F);
      SmallHornLeft.setTextureSize(64, 64);
      SmallHornLeft.mirror = true;
      setRotation(SmallHornLeft, 0F, 0F, -0.2230705F);
      Head = new ModelRenderer(this, 36, 28);
      Head.addBox(0F, 0F, 0F, 5, 5, 5);
      Head.setRotationPoint(-3F, 14F, -10F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      TuftRight = new ModelRenderer(this, 31, 0);
      TuftRight.addBox(0F, 0F, 0F, 2, 4, 2);
      TuftRight.setRotationPoint(2F, 14F, -7F);
      TuftRight.setTextureSize(64, 64);
      TuftRight.mirror = true;
      setRotation(TuftRight, 0F, 0F, 0F);
      TuftLeft = new ModelRenderer(this, 22, 0);
      TuftLeft.addBox(0F, 0F, 0F, 2, 4, 2);
      TuftLeft.setRotationPoint(-5F, 14F, -7F);
      TuftLeft.setTextureSize(64, 64);
      TuftLeft.mirror = true;
      setRotation(TuftLeft, 0F, 0F, 0F);
      TuftEdgeLeft = new ModelRenderer(this, 0, 8);
      TuftEdgeLeft.addBox(0F, 0F, 0F, 1, 2, 1);
      TuftEdgeLeft.setRotationPoint(-6F, 15F, -6F);
      TuftEdgeLeft.setTextureSize(64, 64);
      TuftEdgeLeft.mirror = true;
      setRotation(TuftEdgeLeft, 0F, 0F, 0F);
      TailBack = new ModelRenderer(this, 35, 9);
      TailBack.addBox(0F, 0F, 0F, 1, 1, 4);
      TailBack.setRotationPoint(-1F, 18.5F, 10.6F);
      TailBack.setTextureSize(64, 64);
      TailBack.mirror = true;
      setRotation(TailBack, -0.6145831F, 0F, 0F);
      BackLegLeft = new ModelRenderer(this, 0, 31);
      BackLegLeft.addBox(0F, 0F, 0F, 2, 5, 2);
      BackLegLeft.setRotationPoint(-3F, 19F, 5F);
      BackLegLeft.setTextureSize(64, 64);
      BackLegLeft.mirror = true;
      setRotation(BackLegLeft, 0F, 0F, 0F);
      FrontLegRight = new ModelRenderer(this, 27, 31);
      FrontLegRight.addBox(0F, 0F, 0F, 2, 5, 2);
      FrontLegRight.setRotationPoint(0F, 19F, -4F);
      FrontLegRight.setTextureSize(64, 64);
      FrontLegRight.mirror = true;
      setRotation(FrontLegRight, 0F, 0F, 0F);
      PawBackLeft = new ModelRenderer(this, 21, 39);
      PawBackLeft.addBox(0F, 0F, 0F, 2, 1, 1);
      PawBackLeft.setRotationPoint(-3F, 23F, 4F);
      PawBackLeft.setTextureSize(64, 64);
      PawBackLeft.mirror = true;
      setRotation(PawBackLeft, 0F, 0F, 0F);
      TailFurEdge = new ModelRenderer(this, 9, 6);
      TailFurEdge.addBox(0F, 0F, 0F, 1, 3, 4);
      TailFurEdge.setRotationPoint(-1F, 18.63333F, 13F);
      TailFurEdge.setTextureSize(64, 64);
      TailFurEdge.mirror = true;
      setRotation(TailFurEdge, -0.6472177F, 0F, 0F);
      Neck = new ModelRenderer(this, 13, 0);
      Neck.addBox(0F, 0F, 0F, 3, 3, 1);
      Neck.setRotationPoint(-2F, 16F, -5F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      TailMiddle = new ModelRenderer(this, 35, 14);
      TailMiddle.addBox(0F, 0F, 0F, 2, 2, 5);
      TailMiddle.setRotationPoint(-1.5F, 16.5F, 6F);
      TailMiddle.setTextureSize(64, 64);
      TailMiddle.mirror = true;
      setRotation(TailMiddle, -0.2974289F, 0F, 0F);
      FrontLegLeft = new ModelRenderer(this, 18, 31);
      FrontLegLeft.addBox(0F, 0F, 0F, 2, 5, 2);
      FrontLegLeft.setRotationPoint(-3F, 19F, -4F);
      FrontLegLeft.setTextureSize(64, 64);
      FrontLegLeft.mirror = true;
      setRotation(FrontLegLeft, 0F, 0F, 0F);
      PawFrontLeft = new ModelRenderer(this, 0, 39);
      PawFrontLeft.addBox(0F, 0F, 0F, 2, 1, 1);
      PawFrontLeft.setRotationPoint(-3F, 23F, -5F);
      PawFrontLeft.setTextureSize(64, 64);
      PawFrontLeft.mirror = true;
      setRotation(PawFrontLeft, 0F, 0F, 0F);
      PawFrontRight = new ModelRenderer(this, 7, 39);
      PawFrontRight.addBox(0F, 0F, 0F, 2, 1, 1);
      PawFrontRight.setRotationPoint(0F, 23F, -5F);
      PawFrontRight.setTextureSize(64, 64);
      PawFrontRight.mirror = true;
      setRotation(PawFrontRight, 0F, 0F, 0F);
      PawBackRight = new ModelRenderer(this, 14, 39);
      PawBackRight.addBox(0F, 0F, 0F, 2, 1, 1);
      PawBackRight.setRotationPoint(0F, 23F, 4F);
      PawBackRight.setTextureSize(64, 64);
      PawBackRight.mirror = true;
      setRotation(PawBackRight, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 14);
      Body.addBox(0F, 0F, 0F, 5, 4, 11);
      Body.setRotationPoint(-3F, 15.5F, -4F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, -0.0523599F, 0F, 0F);
      BackFur = new ModelRenderer(this, 0, 42);
      BackFur.addBox(0F, 0F, 0F, 1, 2, 11);
      BackFur.setRotationPoint(-1F, 14.5F, -4F);
      BackFur.setTextureSize(64, 64);
      BackFur.mirror = true;
      setRotation(BackFur, -0.0523599F, 0F, 0F);
      TailMiddleFur = new ModelRenderer(this, 25, 42);
      TailMiddleFur.addBox(0F, 0F, 0F, 1, 2, 4);
      TailMiddleFur.setRotationPoint(-1F, 15.5F, 7F);
      TailMiddleFur.setTextureSize(64, 64);
      TailMiddleFur.mirror = true;
      setRotation(TailMiddleFur, -0.3126102F, 0F, 0F);
      TailBackFur = new ModelRenderer(this, 25, 49);
      TailBackFur.addBox(0F, 0F, 0F, 1, 1, 3);
      TailBackFur.setRotationPoint(-1F, 17.45555F, 11F);
      TailBackFur.setTextureSize(64, 64);
      TailBackFur.mirror = true;
      setRotation(TailBackFur, -0.6485534F, 0F, 0F);
      Collar = new ModelRenderer(this, 49, 42);
      Collar.addBox(0F, 0F, 0F, 1, 1, 1);
      Collar.setRotationPoint(-1F, 20F, -5F);
      Collar.setTextureSize(64, 64);
      Collar.mirror = true;
      setRotation(Collar, 0F, 0F, 0F);
      CollarBell = new ModelRenderer(this, 36, 42);
      CollarBell.addBox(-2F, -2F, 0F, 5, 5, 1);
      CollarBell.setRotationPoint(-1F, 17F, -5F);
      CollarBell.setTextureSize(64, 64);
      CollarBell.mirror = true;
      setRotation(CollarBell, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Snout.render(par7);
    LargeHornRight.render(par7);
    TuftEdgeRight.render(par7);
    BackLegRight.render(par7);
    SmallHornRight.render(par7);
    LargeHornLeft.render(par7);
    SmallHornLeft.render(par7);
    Head.render(par7);
    TuftRight.render(par7);
    TuftLeft.render(par7);
    TuftEdgeLeft.render(par7);
    TailBack.render(par7);
    BackLegLeft.render(par7);
    FrontLegRight.render(par7);
    PawBackLeft.render(par7);
    TailFurEdge.render(par7);
    Neck.render(par7);
    TailMiddle.render(par7);
    FrontLegLeft.render(par7);
    PawFrontLeft.render(par7);
    PawFrontRight.render(par7);
    PawBackRight.render(par7);
    Body.render(par7);
    BackFur.render(par7);
    TailMiddleFur.render(par7);
    TailBackFur.render(par7);
    Collar.render(par7);
    CollarBell.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
	super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
